name: Audit

on: { workflow_call: {} }

jobs:
  audit:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - name: Run audit
        uses: soltiHQ/actions/taskfile@main
        with: { command: cargo/audit }