name: Checks

on: { workflow_call: {} }

jobs:
  fmt:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - name: Run fmt
        uses: soltiHQ/actions/taskfile@main
        with: { command: cargo/fmt }

  check:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - name: Run check
        uses: soltiHQ/actions/taskfile@main
        with: { command: cargo/check }

  test:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Cache
        id: cache_get
        uses: ./.github/actions/cache-get
        with: { job_name: test }

      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: cargo/test }

      - name: Put Cache
        if: steps.cache_get.outputs.cache-hit != 'true'
        uses: ./.github/actions/cache-put
        with: { job_name: test }

  clippy:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Cache
        id: cache_get
        uses: ./.github/actions/cache-get
        with: { job_name: clippy }

      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: cargo/clippy }

      - name: Put Cache
        if: steps.cache_get.outputs.cache-hit != 'true'
        uses: ./.github/actions/cache-put
        with: { job_name: clippy }